POST http://localhost:3000/criajogo
Content-Type: application/json

###

POST http://localhost:3000/jogo/move
Content-Type: application/json

{
  "jogoColuna": 5
}

###

POST http://localhost:3000/jogo/move
Content-Type: application/json

{
  "jogoColuna": 4
}