
#Inicializa novo jogo (reset database)
POST http://localhost:3000/criajogo
Content-Type: application/json

###

#Joga peça na coluna 5
POST http://localhost:3000/jogo/move
Content-Type: application/json

{
  "jogoColuna": 5
}

###

#Joga peça na coluna 4
POST http://localhost:3000/jogo/move
Content-Type: application/json

{
  "jogoColuna": 4
}

###

#Obtém estado do jogo
GET http://localhost:3000/jogo
Content-Type: application/json